create table if not exists public.aiscore_private_settings (
  id text primary key,
  secret_value text,
  updated_at timestamptz not null default now()
);

create table if not exists public.aiscore_api_cache (
  cache_key text primary key,
  payload jsonb not null,
  source_updated_at timestamptz,
  expires_at timestamptz not null,
  updated_at timestamptz not null default now()
);
create index if not exists aiscore_api_cache_expires_idx on public.aiscore_api_cache(expires_at);

create table if not exists public.aiscore_odds_history (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null,
  signal_key text not null,
  market text,
  selection text,
  line numeric,
  bookmaker text,
  odds numeric not null check (odds > 1),
  captured_at timestamptz not null default now()
);
create index if not exists aiscore_odds_history_fixture_idx on public.aiscore_odds_history(fixture_id,captured_at);
create index if not exists aiscore_odds_history_signal_idx on public.aiscore_odds_history(fixture_id,signal_key,captured_at);

create table if not exists public.aiscore_analyses (
  id bigint generated by default as identity primary key,
  fixture_id bigint not null,
  mode text not null check (mode in ('prematch','live')),
  league_id bigint,
  league_name text,
  home_team_id bigint,
  home_team_name text,
  away_team_id bigint,
  away_team_name text,
  match_date timestamptz,
  match_status text,
  minute integer,
  score_home integer,
  score_away integer,
  state_hash text not null,
  data_quality text not null check (data_quality in ('HIGH','MEDIUM','LOW')),
  data_quality_score numeric not null default 0,
  confidence text not null check (confidence in ('HIGH','MEDIUM','LOW')),
  verdict text not null check (verdict in ('IGRAJ','CEKAJ','PRESKOCI')),
  analysis_generated_at timestamptz not null default now(),
  data_last_updated timestamptz,
  source_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique (fixture_id,mode,state_hash)
);
create index if not exists aiscore_analyses_fixture_idx on public.aiscore_analyses(fixture_id,mode,created_at desc);
create index if not exists aiscore_analyses_created_idx on public.aiscore_analyses(created_at desc);

create table if not exists public.aiscore_analysis_picks (
  id bigint generated by default as identity primary key,
  analysis_id bigint not null references public.aiscore_analyses(id) on delete cascade,
  pick_rank integer not null check (pick_rank between 1 and 3),
  signal_key text not null,
  market text not null,
  selection text not null,
  line numeric,
  bookmaker text,
  odds numeric,
  odds_timestamp timestamptz,
  ai_probability numeric,
  implied_probability numeric,
  fair_odds numeric,
  edge_pp numeric,
  ev_pct numeric,
  confidence text not null check (confidence in ('HIGH','MEDIUM','LOW')),
  stake_units numeric not null default 0 check (stake_units >= 0 and stake_units <= 1.5),
  status text not null,
  result text check (result is null or result in ('WIN','LOSS','VOID')),
  closing_odds numeric,
  clv_pct numeric,
  settled_at timestamptz,
  why text,
  main_risk text,
  created_at timestamptz not null default now(),
  unique (analysis_id,pick_rank)
);
create index if not exists aiscore_picks_analysis_idx on public.aiscore_analysis_picks(analysis_id);
create index if not exists aiscore_picks_result_idx on public.aiscore_analysis_picks(result,created_at desc);
create index if not exists aiscore_picks_market_idx on public.aiscore_analysis_picks(market,created_at desc);

create table if not exists public.aiscore_model_reviews (
  id bigint generated by default as identity primary key,
  pick_id bigint not null unique references public.aiscore_analysis_picks(id) on delete cascade,
  review jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.aiscore_private_settings enable row level security;
alter table public.aiscore_api_cache enable row level security;
alter table public.aiscore_odds_history enable row level security;
alter table public.aiscore_analyses enable row level security;
alter table public.aiscore_analysis_picks enable row level security;
alter table public.aiscore_model_reviews enable row level security;

revoke all on public.aiscore_private_settings from anon, authenticated;
revoke all on public.aiscore_api_cache from anon, authenticated;
revoke all on public.aiscore_odds_history from anon, authenticated;
revoke all on public.aiscore_analyses from anon, authenticated;
revoke all on public.aiscore_analysis_picks from anon, authenticated;
revoke all on public.aiscore_model_reviews from anon, authenticated;

grant all on public.aiscore_private_settings to service_role;
grant all on public.aiscore_api_cache to service_role;
grant all on public.aiscore_odds_history to service_role;
grant all on public.aiscore_analyses to service_role;
grant all on public.aiscore_analysis_picks to service_role;
grant all on public.aiscore_model_reviews to service_role;
grant usage,select on all sequences in schema public to service_role;
